### ISSUE TITLE
应用和seata-server在同一台设备上面可以启动，要远程访问seata-server就不行

### ISSUE THREAD

**Issue by zengyichang** [seata/seata.github.io#327]
**一、seata server配置**

registry {
  type = "nacos"

  nacos {
    application = "seata-server"
    serverAddr = "192.168.77.23:8848"
    group = "SEATA_GROUP"
    namespace = ""
    cluster = "default"
    username = ""
    password = ""
  }
config {
  type = "nacos"

  nacos {
    serverAddr = "192.168.77.23:8848"
    namespace = ""
    group = "SEATA_GROUP"
    username = ""
    password = ""
    dataId = "seataServer.properties"
  }

service {
  #transaction service group mapping
  vgroupMapping.my_test_tx_group = "default"
  #only support when registry.type=file, please don't set multiple addresses
  default.grouplist = "192.168.77.23:8091"
  #degrade, current not support
  enableDegrade = false
  #disable seata
  disableGlobalTransaction = false
}

启动 nohup sh seata-server.sh -p 8091 -h 192.168.77.23 -m file &

**二、应用配置**
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.77.23:8848
      config:
        enabled: true
        server-addr: 192.168.77.23:8848
        file-extension: properties
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

三、报错信息

**重点打包在192.168.77.23服务器上面可以正常启动，本地电脑不能启动，是缺少什么配置吗？**

2021-05-27 17:11:44.341 ERROR 34172 --- [           main] i.s.c.r.netty.NettyClientChannelManager  : 0101 can not connect to 127.0.0.1:8091 cause:can not register RM,err:can not connect to services-server.

io.seata.common.exception.FrameworkException: can not register RM,err:can not connect to services-server.
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:210) ~[seata-all-1.3.0.jar:1.3.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:103) ~[seata-all-1.3.0.jar:1.3.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:175) ~[seata-all-1.3.0.jar:1.3.0]
	at io.seata.core.rpc.netty.RmNettyRemotingClient.registerResource(RmNettyRemotingClient.java:181) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.rm.AbstractResourceManager.registerResource(AbstractResourceManager.java:121) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.rm.datasource.DataSourceManager.registerResource(DataSourceManager.java:146) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.rm.DefaultResourceManager.registerResource(DefaultResourceManager.java:114) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.rm.datasource.DataSourceProxy.init(DataSourceProxy.java:99) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:85) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:74) [seata-all-1.3.0.jar:1.3.0]
	at com.kocla.cloud.erp.config.DataSourceConfiguration.dataSourceProxy(DataSourceConfiguration.java:38) [classes/:na]

服务器正常启动
![image](https://user-images.githubusercontent.com/38252982/119805552-ed36af80-bf13-11eb-89e7-171db0584e09.png)

**Comment by lvekee** [comment]
默认会连接本机的seata 客户端需要配置seata.registry下的相关配置
