### ISSUE TITLE
为什么会有127.0.0.1，我都全是远程ip，can not connect to 127.0.0.1:8091 cause:can not register RM,err:can not connect to services-server

### ISSUE THREAD

**Issue by zengyichang** [seata/seata.github.io#328]
2021-05-28 11:33:21.526  INFO 36540 --- [           main] i.s.core.rpc.netty.NettyPoolableFactory  : NettyPool create channel to transactionRole:RMROLE,address:127.0.0.1:8091,msg:< RegisterRMRequest{resourceIds='jdbc:mysql://192.168.77.23:3306/koala_deve', applicationId='erp-service', transactionServiceGroup='my_test_tx_group'} >
2021-05-28 11:33:22.693 ERROR 36540 --- [           main] i.s.c.r.netty.NettyClientChannelManager  : 0304 register RM failed.

io.seata.common.exception.FrameworkException: can not connect to services-server.
	at io.seata.core.rpc.netty.NettyClientBootstrap.getNewChannel(NettyClientBootstrap.java:182) ~[seata-all-1.3.0.jar:1.3.0]
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:58) ~[seata-all-1.3.0.jar:1.3.0]
	at io.seata.core.rpc.netty.NettyPoolableFactory.makeObject(NettyPoolableFactory.java:34) ~[seata-all-1.3.0.jar:1.3.0]
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220) ~[commons-pool-1.6.jar:1.6]
	at io.seata.core.rpc.netty.NettyClientChannelManager.doConnect(NettyClientChannelManager.java:206) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.acquireChannel(NettyClientChannelManager.java:103) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:175) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.core.rpc.netty.RmNettyRemotingClient.registerResource(RmNettyRemotingClient.java:181) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.rm.AbstractResourceManager.registerResource(AbstractResourceManager.java:121) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.rm.datasource.DataSourceManager.registerResource(DataSourceManager.java:146) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.rm.DefaultResourceManager.registerResource(DefaultResourceManager.java:114) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.rm.datasource.DataSourceProxy.init(DataSourceProxy.java:99) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:85) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:74) [seata-all-1.3.0.jar:1.3.0]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_221]
	at io.seata.spring.annotation.datasource.DataSourceProxyHolder.putDataSource(DataSourceProxyHolder.java:64) ~[seata-all-1.3.0.jar:1.3.0]
	at io.seata.spring.annotation.datasource.SeataAutoDataSourceProxyAdvice.invoke(SeataAutoDataSourceProxyAdvice.java:34) ~[seata-all-1.3.0.jar:1.3.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.alibaba.druid.pool.DruidDataSource$$EnhancerBySpringCGLIB$$b17df98f.toString(<generated>) ~[druid-1.1.6.jar:1.1.6]
	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:85) [seata-all-1.3.0.jar:1.3.0]
	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:74) [seata-all-1.3.0.jar:1.3.0]
	at com.kocla.cloud.erp.config.DataSourceConfiguration.dataSourceProxy(DataSourceConfiguration.java:38) ~[classes/:na]
	at com.kocla.cloud.erp.config.DataSourceConfiguration$$EnhancerBySpringCGLIB$$da7e9b12.CGLIB$dataSourceProxy$1(<generated>) ~[classes/:na]
	at com.kocla.cloud.erp.config.DataSourceConfiguration$$EnhancerBySpringCGLIB$$da7e9b12$$FastClassBySpringCGLIB$$bc9c29e.invoke(<generated>) ~[classes/:na]

**Comment by a364176773** [comment]
官网教程仔细看 server暴露的时候-h

**Comment by zengyichang** [comment]
> 官网教程仔细看 server暴露的时候-h

加了-h 指定是外网
nohup sh seata-server.sh -p 8091 -h 114.55.93.87 -m file

**Comment by a364176773** [comment]
> > 官网教程仔细看 server暴露的时候-h
> 
> 启动加了-h 指定是外网不行
> nohup sh seata-server.sh -p 8091 -h 114.55.93.87 -m file

你指定内网ip呀

**Comment by zengyichang** [comment]
加了-h 指定是外网
nohup sh seata-server.sh -p 8091 -h 114.55.93.87 -m file


> 
> 
> > > 官网教程仔细看 server暴露的时候-h
> > 
> > 
> > 启动加了-h 指定是外网不行
> > nohup sh seata-server.sh -p 8091 -h 114.55.93.87 -m file
> 
> 你指定内网ip呀

nohup sh seata-server.sh -p 8091 -h 127.0.0.1 -m file
也不行

**Comment by a364176773** [comment]
升级1.3教程: https://www.bilibili.com/video/BV1Cf4y1X7vR
springcloud整合demo:

https://gitee.com/itCjb/spring-cloud-alibaba-seata-demo 
（上述demo内附1.3整合文字版）
